(async () => {
const fs = require('fs');
const root = '/Users/jaili/projects/godot/outpost';
const source = root + '/assets/models/city';
const base = source + '/street_mobility';
for (const dir of ['blockbench', 'gltf', 'textures', 'review']) fs.mkdirSync(base + '/' + dir, {recursive:true});
const names = ['sedan', 'van', 'ambulance', 'bus', 'forklift'];
const records = [];
const font = {S:['111','100','111','001','111'],T:['111','010','010','010','010'],O:['111','101','101','101','111'],P:['110','101','110','100','100'],B:['110','101','110','101','110'],U:['101','101','101','101','111'],A:['010','101','111','101','101'],R:['110','101','110','101','101'],K:['101','101','110','101','101'],I:['111','010','010','010','111'],N:['101','111','111','111','101'],G:['111','100','101','101','111']};
const originals = Object.fromEntries(fs.readdirSync(source+'/textures').filter(n=>n.endsWith('.png')).map(n=>[n.slice(0,-4),'data:image/png;base64,'+fs.readFileSync(source+'/textures/'+n).toString('base64')]));
function painted(name, background, draw) {
 const c=document.createElement('canvas');c.width=c.height=32;const x=c.getContext('2d');x.imageSmoothingEnabled=false;x.fillStyle=background;x.fillRect(0,0,32,32);draw(x);
 originals[name]=c.toDataURL('image/png');
}
function text(x,word,y,color='#e0d7b7') {x.fillStyle=color;const start=(32-word.length*4+1)/2;[...word].forEach((c,i)=>(font[c]||[]).forEach((r,yy)=>[...r].forEach((v,xx)=>{if(v==='1')x.fillRect(Math.floor(start)+i*4+xx,y+yy,1,1);})));}
painted('stop_face','#823f32',x=>{x.strokeStyle='#dfd6b6';x.lineWidth=2;x.beginPath();[[10,2],[22,2],[30,10],[30,22],[22,30],[10,30],[2,22],[2,10]].forEach((p,i)=>i?x.lineTo(...p):x.moveTo(...p));x.closePath();x.stroke();text(x,'STOP',14);});
painted('bus_face','#465d54',x=>{x.fillStyle='#d8d0ab';x.fillRect(1,1,30,1);x.fillRect(1,30,30,1);text(x,'BUS',4);x.fillRect(8,13,16,11);x.fillStyle='#33423d';x.fillRect(10,15,12,5);x.fillRect(9,24,3,3);x.fillRect(20,24,3,3);});
painted('timetable','#cec9ae',x=>{x.fillStyle='#465d54';x.fillRect(2,2,28,5);for(let y=10;y<30;y+=4){x.fillRect(3,y,5,1);x.fillRect(11,y,18,1);}});
painted('signal_red','#af4b36',x=>{x.fillStyle='#da8860';x.fillRect(6,5,10,3);});
painted('signal_amber','#b49a4e',x=>{x.fillStyle='#ddc880';x.fillRect(6,5,10,3);});
painted('signal_green','#6c9360',x=>{x.fillStyle='#a8bd7d';x.fillRect(6,5,10,3);});
painted('lamp_glow','#d8c794',x=>{x.fillStyle='#eee0b3';x.fillRect(4,5,24,22);});
painted('road_zebra',' #41473f'.trim(),x=>{x.fillStyle='#c4c5ac';for(let z=2;z<32;z+=8)x.fillRect(2,z,28,4);});
painted('road_stop_line','#41473f',x=>{x.fillStyle='#c4c5ac';x.fillRect(0,24,32,4);});
painted('road_bus_mark','#41473f',x=>{text(x,'BUS',12,'#c3b67e');x.fillStyle='#c3b67e';x.fillRect(0,0,2,32);x.fillRect(30,0,2,32);});
painted('road_parking','#41473f',x=>{x.fillStyle='#bfc1a7';x.fillRect(0,0,2,32);x.fillRect(30,0,2,32);x.fillRect(0,0,32,2);});
painted('tactile','#a89666',x=>{x.fillStyle='#6f644b';for(let z=3;z<32;z+=6)for(let a=3;a<32;a+=6)x.fillRect(a,z,2,2);});


painted('warm_pavers','#9b8d72',x=>{for(let row=0;row<4;row++){const y=row*8;x.fillStyle='#706650';x.fillRect(0,y,32,1);for(let xx=-16+(row%2)*8;xx<32;xx+=16){x.fillRect(xx,y,1,8);x.fillStyle='#b7a587';x.fillRect(xx+2,y+2,12,1);x.fillStyle='#8b7d63';x.fillRect(xx+2,y+6,12,1);x.fillStyle='#706650';}}});
painted('warm_wood','#836347',x=>{for(let y=0;y<32;y+=8){x.fillStyle='#503e2e';x.fillRect(0,y,32,1);x.fillStyle='#a18358';x.fillRect(1,y+1,30,1);x.fillStyle='#6b4f36';for(let i=0;i<3;i++)x.fillRect((i*13+y)%27,y+4,5,1);}});
painted('iron_dark','#303830',x=>{x.fillStyle='#475044';x.fillRect(2,0,2,32);x.fillStyle='#202820';x.fillRect(28,0,3,32);});
painted('hedge_leaves','#50652d',x=>{for(let i=0;i<45;i++){x.fillStyle=['#354720','#71833c','#93a148','#617635'][i%4];x.fillRect((i*11)%32,(i*7+Math.floor(i/4)*3)%32,3+(i%3),2+(i%2));}});
painted('flower_cream','#d2c392',x=>{x.fillStyle='#f1dfb0';x.fillRect(3,3,24,24);x.fillStyle='#c49d46';x.fillRect(12,12,8,8);});
painted('flower_gold','#b19239',x=>{x.fillStyle='#e1bb55';x.fillRect(3,3,24,24);x.fillStyle='#705834';x.fillRect(12,12,8,8);});
painted('road_center_dash','#41473f',x=>{x.fillStyle='#b99b4d';x.fillRect(15,7,2,18);});
painted('curb_pavers','#9b8d72',x=>{x.fillStyle='#b5a487';x.fillRect(0,0,4,32);x.fillStyle='#625a46';x.fillRect(4,0,1,32);for(let y=0;y<32;y+=8){x.fillRect(0,y,32,1);for(let xx=5;xx<32;xx+=9)x.fillRect(xx,y,1,8);}});
painted('curb_corner_pavers','#9b8d72',x=>{x.fillStyle='#b5a487';x.fillRect(0,0,4,32);x.fillRect(0,28,32,4);x.fillStyle='#625a46';x.fillRect(4,0,1,28);x.fillRect(4,27,28,1);for(let y=0;y<32;y+=8){x.fillRect(0,y,32,1);for(let xx=5;xx<32;xx+=9)x.fillRect(xx,y,1,8);}});
let owned;
function fresh(name) {newProject(Formats.free);owned=Project;Project.name=name;Project.texture_width=Project.texture_height=32;}
function guard(){if(Project!==owned)throw Error('Project selection changed; stopping safely');}
async function material(name) {guard();let t=Texture.all.find(t=>t.name===name+'.png');if(t)return t; t=new Texture({name:name+'.png',width:32,height:32,uv_width:32,uv_height:32,wrap_mode:'repeat'}).fromDataURL(originals[name]).add(false);await new Promise(r=>setTimeout(r,25));t.updateMaterial();return t;}
function group(name,origin=[0,0,0],parent){const g=new Group({name,origin}).init();if(parent)g.addTo(parent);return g;}
function cube(name,lo,hi,mat,parent,full=false){const t=Texture.all.find(t=>t.name===mat+'.png');if(!t)throw Error(mat);const d=hi.map((v,i)=>v-lo[i]),faces={};for(const f of ['north','south','east','west','up','down']){const wh=full?[32,32]:f==='up'||f==='down'?[d[0],d[2]]:f==='east'||f==='west'?[d[2],d[1]]:[d[0],d[1]];faces[f]={uv:[0,0,...wh],texture:t.uuid};}return new Cube({name,from:lo,to:hi,faces,autouv:0}).addTo(parent).init();}

function roundPart(name,x,z,r0,r1,y0,y1,mat,parent,cap=true){const t=Texture.all.find(t=>t.name===mat+'.png');const m=new Mesh({name,vertices:{},faces:{}});for(let i=0;i<12;i++){const a=i*Math.PI/6;m.vertices['a'+i]=[x+Math.cos(a)*r0,y0,z+Math.sin(a)*r0];m.vertices['b'+i]=[x+Math.cos(a)*r1,y1,z+Math.sin(a)*r1];}for(let i=0;i<12;i++){const j=(i+1)%12,vs=['a'+i,'b'+i,'b'+j,'a'+j];m.addFaces(new MeshFace(m,{vertices:vs,uv:Object.fromEntries(vs.map((v,k)=>[v,[[0,y1-y0],[0,0],[3,0],[3,y1-y0]][k]])),texture:t.uuid}));}if(cap){m.vertices.bottom=[x,y0,z];m.vertices.top=[x,y1,z];for(let i=0;i<12;i++){const j=(i+1)%12;for(const vs of [['bottom','a'+i,'a'+j],['top','b'+j,'b'+i]])m.addFaces(new MeshFace(m,{vertices:vs,uv:Object.fromEntries(vs.map(v=>[v,[(m.vertices[v][0]-x+r0),(m.vertices[v][2]-z+r0)]])),texture:t.uuid}));}}m.addTo(parent).init();return m;}
function lantern(x,y,z,g){roundPart('lantern_foot',x,z,3.7,3,y,y+1,'iron_dark',g);cube('warm_glass',[x-2.1,y+1,z-2.1],[x+2.1,y+9,z+2.1],'lamp_glow',g,true);for(const a of [-2.6,2.1])for(const b of [-2.6,2.1])cube('lantern_frame',[x+a,y+1,z+b],[x+a+.5,y+10,z+b+.5],'iron_dark',g);roundPart('lantern_roof',x,z,4.3,1,y+10,y+13,'iron_dark',g);roundPart('finial',x,z,1,.25,y+13,y+15,'iron_dark',g);}
function clip(name,length,loop,tracks){const a=new Animation({name,length,loop}).add();for(const [g,channel,keys] of tracks){const b=a.getBoneAnimator(g);for(const [time,v] of keys)b.addKeyframe({channel,time,interpolation:'linear',data_points:[{x:v[0],y:v[1],z:v[2]}]});}return a;}
async function save(name,meta,keep=false){guard();Animator.preview();Modes.options.edit.select();Canvas.updateAll();const raw=Codecs.project.compile({raw:true,bitmaps:true});for(const t of raw.textures)fs.writeFileSync(base+'/textures/'+t.name,Buffer.from(t.source.split(',')[1],'base64'));raw.outpost={...meta,tile_pixels:32,units_per_tile:32,stage:'Native Blockbench review; engine driving integration pending'};fs.writeFileSync(base+'/blockbench/'+name+'.bbmodel',JSON.stringify(raw));const result=await Codecs.gltf.compile({encoding:'ascii',scale:16,embed_textures:true,animations:true});const gltf=typeof result==='string'?JSON.parse(result):result;for(const m of gltf.materials||[]){m.pbrMetallicRoughness.metallicFactor=0;m.pbrMetallicRoughness.roughnessFactor=1;if((m.name||'').includes('lamp_glow'))m.emissiveFactor=[0.65,0.57,0.34];}for(const s of gltf.samplers||[]){s.magFilter=s.minFilter=9728;s.wrapS=s.wrapT=10497;}fs.writeFileSync(base+'/gltf/'+name+'.gltf',JSON.stringify(gltf));records.push({id:name,...meta,elements:raw.elements.length,animations:Animator.animations.map(a=>a.name),gltf_animations:(gltf.animations||[]).map(a=>a.name)});Project.save_path=base+'/blockbench/'+name+'.bbmodel';Project.saved=true;if(!keep)await Project.close();}
for(const name of names){
 fresh(name+'_animated');const raw=JSON.parse(fs.readFileSync(source+'/blockbench/'+name+'.bbmodel','utf8'));Codecs.project.parse(raw,source+'/blockbench/'+name+'.bbmodel');Project.name=name+'_animated';await new Promise(r=>setTimeout(r,160));
 const roots=[...Outliner.root],vehicle=group('vehicle_root'),body=group('body_suspension',[0,12,0],vehicle),wheels=[],steers=[];
 for(const g of roots){if(!g.name.startsWith('round_wheel_')){g.addTo(body);continue;}const tire=g.children.find(e=>e.name==='tire');const pts=Object.values(tire.vertices);const center=[0,1,2].map(i=>(Math.min(...pts.map(p=>p[i]))+Math.max(...pts.map(p=>p[i])))/2);const tag=(center[2]<0?'front':'rear')+'_'+(center[0]<0?'left':'right');g.name='wheel_'+tag;g.origin=Array.from(center);g.addTo(vehicle);wheels.push(g);const steerAxle=name==='forklift'?center[2]>0:center[2]<0;if(steerAxle){const s=group('steer_'+tag,center,vehicle);g.addTo(s);steers.push(s);}}
 const wb=Math.max(...wheels.map(w=>w.origin[2]))-Math.min(...wheels.map(w=>w.origin[2]));
 const radius=name==='forklift'?6:7;const tracks=(direction=1)=>wheels.map(w=>[w,'rotation',Array.from({length:5},(_,i)=>[i/4,[-direction*90*i,0,0]])]);
 clip('idle',1.2,'loop',[[body,'position',[[0,[0,0,0]],[.3,[0,.12,0]],[.6,[0,0,0]],[.9,[0,.12,0]],[1.2,[0,0,0]]]]]);
 clip('drive_forward',1,'loop',tracks());clip('reverse',1,'loop',tracks(-1));
 for(const side of [-1,1]){const sideName=side===1?'left':'right';const yaw=(name==='forklift'?-1:1)*side*25;clip('steer_'+sideName,.25,'hold',steers.map(g=>[g,'rotation',[[0,[0,0,0]],[.25,[0,yaw,0]]]]));for(const direction of [1,-1]){const turn=tracks(direction);for(const g of steers)turn.push([g,'rotation',[[0,[0,yaw,0]],[1,[0,yaw,0]]]]);clip((direction===1?'turn_':'reverse_turn_')+sideName,1,'loop',turn);}}
 clip('steer_center',.25,'hold',steers.map(g=>[g,'rotation',[[0,[0,0,0]],[.25,[0,0,0]]]]));
 clip('brake',.6,'once',[[body,'rotation',[[0,[0,0,0]],[.15,[2,0,0]],[.35,[-.5,0,0]],[.6,[0,0,0]]]]]);
 for(const direction of [1,-1]){const t=tracks(direction);t.push([vehicle,'position',[[0,[0,0,0]],[1,[0,0,-direction*2*Math.PI*radius]]]]);clip('preview_'+(direction===1?'forward':'reverse'),1,'once',t);}
 for(const side of [1,-1]){const t=[],duration=2,R=wb/Math.tan(25*Math.PI/180);for(const w of wheels){const keys=[];for(let i=0;i<=16;i++){const a=i/16*Math.PI/4;keys.push([duration*i/16,[-a*R/radius*180/Math.PI,0,0]]);}t.push([w,'rotation',keys]);}t.push([vehicle,'position',Array.from({length:17},(_,i)=>{const a=i/16*Math.PI/4;return [duration*i/16,[-side*R*(1-Math.cos(a)),0,-R*Math.sin(a)]];})]);t.push([vehicle,'rotation',Array.from({length:17},(_,i)=>[duration*i/16,[0,side*i/16*45,0]])]);for(const g of steers)t.push([g,'rotation',[[0,[0,(name==='forklift'?-1:1)*side*25,0]],[2,[0,(name==='forklift'?-1:1)*side*25,0]]]]);clip('preview_turn_'+(side===1?'left':'right'),duration,'once',t);}
 if(name==='forklift'){const fork=Group.all.find(g=>g.name==='fork');clip('fork_raise',1,'hold',[[fork,'position',[[0,[0,0,0]],[1,[0,20,0]]]]]);clip('fork_lower',1,'hold',[[fork,'position',[[0,[0,20,0]],[1,[0,0,0]]]]]);}
 await save(name,{category:'vehicle',source:'../blockbench/'+name+'.bbmodel',forward_axis:'-Z',wheel_radius:radius,wheelbase:wb,steering_axle:name==='forklift'?'rear':'front',steering_limit_degrees:25,root_motion:'Only preview_* clips translate vehicle_root; runtime clips are in place'},true);
}
async function prop(name,mats,build){fresh(name);for(const m of mats)await material(m);const g=group(name);await build(g);await save(name,{category:'street_prop',anchor:'base_y_0'});}
const metal='vehicle_metal',dark='vehicle_trim',cream='vehicle_cream';
await prop('stop_sign',[metal,'stop_face'],g=>{cube('foot',[-3,0,-3],[3,1,3],metal,g);cube('post',[-.8,1,-.8],[.8,43,.8],metal,g);const pts=[[-5,50],[5,50],[10,45],[10,35],[5,30],[-5,30],[-10,35],[-10,45]];const m=new Mesh({name:'octagonal_stop_plate',vertices:{},faces:{}});pts.forEach((p,i)=>{m.vertices['a'+i]=[p[0],p[1],-1.2];m.vertices['b'+i]=[p[0],p[1],-.2];});for(let i=1;i<7;i++)m.addFaces(new MeshFace(m,{vertices:['a0','a'+i,'a'+(i+1)],uv:Object.fromEntries([0,i,i+1].map(k=>['a'+k,[(10-pts[k][0])*1.6,(50-pts[k][1])*1.6]])),texture:Texture.all.find(t=>t.name==='stop_face.png').uuid}));for(let i=1;i<7;i++)m.addFaces(new MeshFace(m,{vertices:['b0','b'+(i+1),'b'+i],uv:Object.fromEntries([0,i,i+1].map(k=>['b'+k,[0,0]])),texture:Texture.all.find(t=>t.name===metal+'.png').uuid}));for(let i=0;i<8;i++){const j=(i+1)%8,vs=['a'+i,'b'+i,'b'+j,'a'+j];m.addFaces(new MeshFace(m,{vertices:vs,uv:Object.fromEntries(vs.map((v,k)=>[v,[k%2,Math.floor(k/2)]])),texture:Texture.all.find(t=>t.name===metal+'.png').uuid}));}m.addTo(g).init();});
for(const double of [false,true])await prop(double?'street_light_double':'street_light',['iron_dark','lamp_glow'],g=>{roundPart('plinth',0,0,3.8,3,0,3,'iron_dark',g);roundPart('pedestal',0,0,2,1.2,3,11,'iron_dark',g);roundPart('slender_column',0,0,1.1,.7,11,50,'iron_dark',g);roundPart('collar',0,0,1.5,1.5,46,48,'iron_dark',g);if(double){cube('cross_arm',[-11,48,-.6],[11,49,.6],'iron_dark',g);for(const x of [-10,10]){cube('brace',[Math.min(0,x),46,-.45],[Math.max(0,x),47,.45],'iron_dark',g);lantern(x,49,0,g);}}else lantern(0,49,0,g);});
await prop('bus_stop_sign',[metal,'bus_face','timetable'],g=>{cube('base',[-2,0,-2],[2,1,2],metal,g);cube('post',[-.75,1,-.5],[.75,56,.5],metal,g);cube('route_sign',[-7,41,-1],[7,57,0],'bus_face',g,true);cube('timetable',[-4,23,-1],[4,35,0],'timetable',g,true);});
await prop('bus_stop_shelter',['iron_dark','roof','warm_wood',metal,dark,'vehicle_glass','wood','bus_face','timetable'],g=>{for(const x of [-30,30])for(const z of [-9,9])cube('post',[x-1,0,z-1],[x+1,43,z+1],'iron_dark',g);cube('roof',[-33,43,-13],[33,46,13],'roof',g);cube('rear_panel',[-29,12,8],[29,40,9],'vehicle_glass',g);for(const x of [-30,29])cube('side_panel',[x,12,-8],[x+1,40,8],'vehicle_glass',g);cube('bench_seat',[-24,12,1],[17,14,7],'warm_wood',g);for(const x of [-20,13])cube('bench_leg',[x,0,2],[x+2,12,6],'iron_dark',g);cube('bench_back',[-24,16,6],[17,24,7],'warm_wood',g);cube('route_header',[-7,35,-10.1],[7,43,-9.8],'bus_face',g,true);cube('timetable',[20,20,7.7],[27,33,8],'timetable',g,true);});
await prop('trash_can',['iron_dark'],g=>{roundPart('base',0,0,5.8,5.8,0,2,'iron_dark',g);roundPart('barrel',0,0,5.2,5.8,2,18,'iron_dark',g,false);roundPart('inner_liner',0,0,4.7,5.1,2,17.7,'iron_dark',g,false);for(let i=0;i<12;i++){const a=i*Math.PI/6,x=Math.cos(a)*5.5,z=Math.sin(a)*5.5;cube('vertical_rib',[x-.25,2,z-.25],[x+.25,17,z+.25],'iron_dark',g);}const rim=roundPart('open_rim',0,0,6,6,17,18.5,'iron_dark',g,false);roundPart('rim_inner',0,0,5,5,17,18.5,'iron_dark',g,false);for(let i=0;i<12;i++){const a=i*Math.PI/6,b=(i+1)*Math.PI/6,m=new Mesh({name:'rim_top',vertices:{a:[6*Math.cos(a),18.5,6*Math.sin(a)],b:[5*Math.cos(a),18.5,5*Math.sin(a)],c:[5*Math.cos(b),18.5,5*Math.sin(b)],d:[6*Math.cos(b),18.5,6*Math.sin(b)]},faces:{}});m.addFaces(new MeshFace(m,{vertices:['a','b','c','d'],uv:{a:[0,0],b:[0,1],c:[3,1],d:[3,0]},texture:Texture.all[0].uuid}));m.addTo(g).init();}});
await prop('wheelie_bin',[dark,'vehicle_olive',metal],g=>{cube('bin',[-7,2,-6],[7,22,6],'vehicle_olive',g);const lid=group('lid_hinge',[0,23,6],g);cube('lid',[-7.5,22,-6.5],[7.5,23,6.5],dark,lid);cube('handle',[-4,20,6],[4,21,8],metal,g);for(const x of [-7,5])cube('wheel',[x,0,3],[x+2,5,8],dark,g);clip('lid_open',.5,'hold',[[lid,'rotation',[[0,[0,0,0]],[.5,[-100,0,0]]]]]);clip('lid_close',.5,'hold',[[lid,'rotation',[[0,[-100,0,0]],[.5,[0,0,0]]]]]);});
await prop('fire_hydrant',[metal,'vehicle_rust'],g=>{cube('foot',[-4,0,-4],[4,2,4],metal,g);cube('barrel',[-3,2,-3],[3,17,3],'vehicle_rust',g);cube('cap',[-4,16,-4],[4,19,4],'vehicle_rust',g);cube('top_nut',[-1,19,-1],[1,21,1],metal,g);for(const x of [-6,3])cube('hose_outlet',[x,9,-2],[x+3,13,2],metal,g);});
await prop('traffic_cone',[dark,'vehicle_rust',cream],g=>{cube('foot',[-5,0,-5],[5,1,5],dark,g);for(let i=0;i<5;i++){const w=4-i*.65;cube('cone_tier',[-w,1+i*2,-w],[w,3+i*2,w],i===2?cream:'vehicle_rust',g);}});
await prop('street_bollard',[dark,metal,'signal_amber'],g=>{cube('base',[-3,0,-3],[3,1,3],dark,g);cube('post',[-1.5,1,-1.5],[1.5,20,1.5],metal,g);cube('reflector',[-1.6,15,-1.6],[1.6,18,1.6],'signal_amber',g);});
await prop('traffic_signal',[metal,dark,'signal_red','signal_amber','signal_green'],g=>{cube('base',[-3,0,-3],[3,2,3],dark,g);cube('pole',[-1,2,-1],[1,62,1],metal,g);cube('arm',[0,60,-1],[18,62,1],metal,g);cube('housing',[13,40,-3],[23,64,2],dark,g);const lamps=[];for(const [i,color]of ['red','amber','green'].entries()){const y=58-i*7;const lamp=group('signal_'+color,[18,y,-3.2],g);cube('lens',[15,y-2,-3.5],[21,y+2,-3.2],'signal_'+color,lamp);cube('visor',[14,y+2,-6],[22,y+3,-3],dark,g);lamps.push(lamp);}for(const [i,color]of ['red','amber','green'].entries())clip(color,1,'hold',lamps.map((l,k)=>[l,'scale',[[0,k===i?[1,1,1]:[.001,.001,.001]],[1,k===i?[1,1,1]:[.001,.001,.001]]]]));});
await prop('street_bench',['iron_dark','warm_wood'],g=>{for(const x of [-14,12]){cube('front_leg',[x,0,-4],[x+1.5,12,-2.5],'iron_dark',g);cube('rear_leg',[x,0,3.5],[x+1.5,22,5],'iron_dark',g);cube('seat_support',[x,10,-5],[x+1.5,12,5],'iron_dark',g);cube('armrest',[x-.5,17,-5],[x+2,18,5],'warm_wood',g);cube('armrest_post',[x,12,-4],[x+1,17,-3],'iron_dark',g);}for(const z of [-5,-1.5,2])cube('seat_slat',[-18,12,z],[18,13.5,z+3],'warm_wood',g);for(const y of [16.5,20])cube('back_slat',[-18,y,4.5],[18,y+3,5.5],'warm_wood',g);});

for(const flowers of [false,true])await prop(flowers?'flower_planter':'hedge_planter',['brick_red','dirt','hedge_leaves','flower_cream','flower_gold'],g=>{cube('planter_base',[-16,0,-6],[16,1,6],'brick_red',g);cube('soil',[-15,1,-5],[15,7,5],'dirt',g);for(const x of [-16,14.5])cube('end_wall',[x,1,-6],[x+1.5,8,6],'brick_red',g);for(const z of [-6,4.5])cube('long_wall',[-14.5,1,z],[14.5,8,z+1.5],'brick_red',g);for(let i=0;i<5;i++){const x=-12+i*6;cube('leaf_cluster',[x-3,7,-3.5],[x+3.5,flowers?12:17,3.5],'hedge_leaves',g);if(!flowers)cube('leaf_top',[x-2,17,-2],[x+2,19+(i%2),2],'hedge_leaves',g);if(flowers){for(const z of [-2,2]){cube('stem',[x,10,z],[x+.5,15+(i%2),z+.5],'hedge_leaves',g);cube('blossom',[x-1,14+(i%2),z-1],[x+2,15.5+(i%2),z+2],i%2?'flower_gold':'flower_cream',g,true);}}}});
await prop('iron_fence',['iron_dark'],g=>{for(const x of [-15,14]){cube('post',[x,0,-1],[x+1,24,1],'iron_dark',g);roundPart('post_cap',x+.5,0,1.2,.2,24,26,'iron_dark',g);}for(const y of [4,19])cube('rail',[-14,y,-.5],[14,y+1,.5],'iron_dark',g);for(let x=-11;x<=11;x+=4)cube('picket',[x,3,-.4],[x+.7,22,.4],'iron_dark',g);});
for(const [name,top]of [['crosswalk_block','road_zebra'],['stop_line_block','road_stop_line'],['bus_lane_block','road_bus_mark'],['parking_bay_block','road_parking'],['tactile_paving_block','tactile'],['asphalt_block','asphalt'],['sidewalk_block','warm_pavers'],['center_line_block','road_center_dash'],['sidewalk_curb_block','curb_pavers'],['sidewalk_corner_block','curb_corner_pavers']]){fresh(name);await material(top);await material('asphalt');await material('concrete');const g=group(name);const c=cube('solid_32_block',[-16,0,-16],[16,32,16],name.includes('sidewalk')||name.includes('tactile')?'concrete':'asphalt',g,true);c.faces.up.texture=Texture.all.find(t=>t.name===top+'.png').uuid;await save(name,{category:'terrain',anchor:'base_y_0',dimensions:[32,32,32],top_surface_y:32});}
fs.writeFileSync(base+'/catalog.json',JSON.stringify({version:1,source:'Created locally in Blockbench from existing Outpost assets and newly authored geometry',license:'Project-owned source; no third-party assets added',tile_units:32,tile_godot_units:2,assets:records},null,2));
return JSON.stringify({completed:records.length,vehicles:records.filter(a=>a.category==='vehicle').map(a=>({id:a.id,clips:a.animations.length,exported:a.gltf_animations.length})),directory:base});
})()
